#!/bin/bash
set -e -x

# To get consistent builds, files generated by the original build system are
# also committed. This script executes the build system and copies those files
# to `generated/`.

# Running this script is only necessary when updating the dependency in the
# repository, and it's rather much dependant on the environment.

# Updating the dependency involves updating the submodule, running this script,
# and carefully reviewing submodule changes for things that need to be
# reflected in the project build settings.


# Libffi version we're targetting. Should match the submodule.
VERSION="3.0.13"


# Create scratch directory.
SCRATCH="`dirname $0`/../_scratch"
mkdir -p $SCRATCH
cd $SCRATCH

# Download the tarball.
BASENAME="libffi-${VERSION}"
TARBALL="${BASENAME}.tar.gz"
if [ ! -e "${TARBALL}" ]; then
    wget "ftp://sourceware.org/pub/libffi/${TARBALL}"
fi

# Unpack (and trash old scratch dir)
rm -fr "${BASENAME}"
tar -xzf "${TARBALL}"
cd "${BASENAME}"

# Run configure.
./configure \
    --enable-shared \
    --disable-static \
    --disable-builddir

# Copy generated files.
OUT="../../libffi/generated"
mkdir -p "${OUT}/include/"
cp fficonfig.h "${OUT}/"
cp include/ffi.h "${OUT}/include/"
