#!/bin/bash
set -e -x

# To get consistent builds, files generated by the original build system are
# also committed. This script executes the build system and copies those files
# to `generated/`.

# Running this script is only necessary when updating the dependency in the
# repository, and it's rather much dependant on the environment.

# Updating the dependency involves updating the submodule, running this script,
# and carefully reviewing submodule changes for things that need to be
# reflected in the project build settings.


# Create scratch directory.
SCRATCH="`dirname $0`/../_scratch"
mkdir -p $SCRATCH
cd $SCRATCH

# Create a shared clone of the repo.
rm -fr node
git clone --shared ../node/node
cd node

# Fix build dependency problem in V8.
patch -p1 <<EOF
diff --git a/deps/v8/tools/gyp/v8.gyp b/deps/v8/tools/gyp/v8.gyp
index 71cf366..0927b18 100644
--- a/deps/v8/tools/gyp/v8.gyp
+++ b/deps/v8/tools/gyp/v8.gyp
@@ -747,6 +747,7 @@
               ],
             }],
             ['v8_postmortem_support=="true"', {
+              'dependencies': ['postmortem-metadata'],
               'sources': [
                 '<(SHARED_INTERMEDIATE_DIR)/debug-support.cc',
               ]
EOF

# Run configure and make on specific files.
./configure \
    --without-npm \
    --xcode

# Copy generated files.
OUT="../../node/generated"
cp config.gypi "$OUT/"
find . -name '*.xcodeproj' -exec cp -r "{}" "$OUT/" \;
cd "$OUT"

# Rewrite paths in project files.
sed -i '' \
    -e 's|projectDirPath = ""|projectDirPath = "../node/deps/cares"|' \
    -e 's|path = \(.*\)config.gypi|path = \1../generated/config.gypi|' \
    "cares.xcodeproj/project.pbxproj"

sed -i '' \
    -e 's|projectDirPath = ""|projectDirPath = "../node/deps/http_parser"|' \
    -e 's|path = \(.*\)config.gypi|path = \1../generated/config.gypi|' \
    "http_parser.xcodeproj/project.pbxproj"

sed -i '' \
    -e 's|projectDirPath = ""|projectDirPath = "../node/deps/openssl"|' \
    -e 's|path = \(.*\)config.gypi|path = \1../generated/config.gypi|' \
    "openssl.xcodeproj/project.pbxproj"

sed -i '' \
    -e 's|projectDirPath = ""|projectDirPath = "../node/deps/uv"|' \
    -e 's|path = \(.*\)config.gypi|path = \1../generated/config.gypi|' \
    "uv.xcodeproj/project.pbxproj"

sed -i '' \
    -e 's|projectDirPath = ""|projectDirPath = "../node/deps/v8/tools/gyp"|' \
    -e 's|path = \(.*\)config.gypi|path = \1../generated/config.gypi|' \
    "v8.xcodeproj/project.pbxproj"

sed -i '' \
    -e 's|projectDirPath = ""|projectDirPath = "../node/deps/zlib"|' \
    -e 's|path = \(.*\)config.gypi|path = \1../generated/config.gypi|' \
    "zlib.xcodeproj/project.pbxproj"

sed -i '' \
    -e 's|projectDirPath = ""|projectDirPath = "../node"|' \
    -e 's|path = \(.*\)config.gypi|path = \1../generated/config.gypi|' \
    -e 's|\./config.gypi|../generated/config.gypi|g' \
    -e 's|deps/.*/\(.*\.xcodeproj\)|../generated/\1|g' \
    "node.xcodeproj/project.pbxproj"
