#!/bin/bash
set -e -x

# To get consistent builds, files generated by the original build system are
# also committed. This script executes the build system and copies those files
# to `generated/`.

# Running this script is only necessary when updating the dependency in the
# repository, and it's rather much dependant on the environment.

# Updating the dependency involves updating the submodule, running this script,
# and carefully reviewing submodule changes for things that need to be
# reflected in the project build settings.


# Create scratch directory.
SCRATCH="`dirname $0`/../_scratch"
mkdir -p $SCRATCH
cd $SCRATCH

# Create a shared clone of the repo.
rm -fr x264
git clone --shared ../x264/x264
cd x264

# Run configure and make on specific files.
./configure --disable-cli --enable-shared
make common/oclobj.h

# Copy generated files.
OUT="../../x264/generated"
mkdir -p "${OUT}/common/"
cp config.h x264_config.h "${OUT}/"
cp common/oclobj.h "${OUT}/common/"
